
export const CREATE_TRANSACTION = 'app/BigchainDB/CREATE_TRANSACTION'
export const CREATE_TRANSACTION_SUCCESS = 'app/BigchainDB/CREATE_TRANSACTION_SUCCESS'
export const CREATE_TRANSACTION_ERROR = 'app/BigchainDB/CREATE_TRANSACTION_ERROR'
