
export const TRANSFER_TRANSACTION = 'app/BigchainDB/TRANSFER_TRANSACTION'
export const TRANSFER_TRANSACTION_SUCCESS = 'app/BigchainDB/TRANSFER_TRANSACTION_SUCCESS'
export const TRANSFER_TRANSACTION_ERROR = 'app/BigchainDB/TRANSFER_TRANSACTION_ERROR'
